# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a07e6656b1ca1c8ea9e6798c80c2699b63dff3f960894a9125f9753746481fe6d2a221bee5759a6604888d9138221cf87edd3aa0b71d79ae30a89b56f8404f

test:
  secret_key_base: 85f083b6fd9087c3a48569fee5a828c6920cbc126cbc73d675d1d01be772eda3765d12d109e6239acb83a3655616acc4c99812402ce3d2a7ecb480d8bd3d6aa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
